create kafka image and few core utilities (gateway, ip_address).
testcontainers/testcontainers-rs pull request #229
Opened 2020-10-31 07:18 UTC by devcdcc

Hi, there is a image for kafka.
Could someone review that?
Thanks.  :)

2020-11-01 23:14 UTC, thomaseizinger requested changes
Hi @devcdcc !

Thank you for contributing! Please see the inline comments :)

2020-11-01 23:14 UTC, thomaseizinger commented on tests/images.rs
> +        images::zookeeper::Zookeeper::default().with_mapped_port((free_local_port, 2181));
I don't know much about zookeeper and kafka but if these images are supposed to talk to each other, you might want to utilize the functionality for docker networks that was added recently: https://github.com/testcontainers/testcontainers-rs/pull/206

2020-11-01 23:14 UTC, thomaseizinger commented on tests/images.rs
> +        .with_env_var("KAFKA_CFG_ZOOKEEPER_CONNECT", &*zk_urls);
Would it make sense to set these env vars by default within the image?

2020-11-01 23:14 UTC, thomaseizinger commented on tests/images.rs
> +    );
Most of the other tests in here utilize some kind of client library to test the container functionality. Ideally, these tests also act as a form of documentation how to best use these images. Shelling out to bash doesn't feel like the way people would usually use this :)

2020-11-01 23:14 UTC, thomaseizinger commented on src/clients/cli.rs
> +    fn gateway(&self, id: &str) -> String {
Two things regarding these functions:

1. I am not totally convinced we need them and would prefer if we keep the API surface of this traits as small as possible. Like I commented on the test, I believe using docker networks and default ports should make it possible to let the zookeeper and kafka image interact without having to expose this. That would also have the benefit that we provide a better out-of-the-box experience compared to what users currently have to do in a test to set things up properly.

2. IF it turns out that we still need these functions then we should at least reduce the duplication within the implementation. Currently, we have the code for calling `inspect` three times.

2020-12-08 23:21 UTC, devcdcc commented
> Hi @devcdcc !
> 
> Thank you for contributing! Please see the inline comments :)

I am working on it, i just need to include the kafka driver.

2021-09-04 02:19 UTC, thomaseizinger commented
Closing because stale.

2021-09-04 02:19 UTC, closed without merging