Upgrade default bitcoin image version to 0.21.0
testcontainers/testcontainers-rs pull request #261
Opened 2021-02-07 22:25 UTC by bonomat

With the upgrade to 0.21.0 a new startup command was introduced which allows us to execute a script when the startup sequence was completed. We simply echo `bitcoind startup sequence completed.`.
This allows us to remove `-debug` which keeps the bitcoind log _clean_.
Note: this release also removed the default wallet.

FYI:

2021-02-07 23:52 UTC, thomaseizinger requested changes
Thank you!

Can you also include a line in the CHANGELOG please with a link to `bitcoind`'s changelog?

2021-02-07 23:52 UTC, thomaseizinger commented on src/images/coblox_bitcoincore.rs
> +            WaitFor::message_on_stdout("bitcoind startup sequence completed."),
To make the relationship between these constants clearer, can we extract this into a non-pub `const` and use `format!` above to configure the command?

2021-02-08 03:23 UTC, thomaseizinger approved these changes
Thanks, looks good!

2021-02-11 22:27 UTC, D4nte approved these changes

2021-02-19 04:20 UTC, thomaseizinger commented
@bonomat can you rebase this please?

2021-02-19 06:06 UTC, bonomat commented
🤦‍♂️rebased against master

2021-02-19 06:08 UTC, bonomat commented
bors r+

2021-02-19 06:17 UTC, merged