Support container networking
testcontainers/testcontainers-rs pull request #320
Opened 2021-12-14 14:54 UTC by jhershberg

This is simply a matter of only exposing ports if
the network does not start_with("container:").
Issue is https://github.com/testcontainers/testcontainers-rs/issues/319

Signed-off-by: Josh Hershberg <yehoshua@redis.com>

2021-12-16 05:03 UTC, thomaseizinger requested changes
One comment, otherwise happy to merge this!

2021-12-16 09:29 UTC, jhershberg commented on src/clients/cli.rs
> +        let is_container_networked = is_container_networked;
Oh, the basic idea is to remove the mutability:
https://rust-unofficial.github.io/patterns/idioms/temporary-mutability.html

Not critical, happy to take it out if you prefer.

2021-12-16 09:30 UTC, jhershberg commented
> One comment, otherwise happy to merge this!

Thanks!

2021-12-20 06:24 UTC, thomaseizinger commented on src/clients/cli.rs
> +        let is_container_networked = is_container_networked;
Right, if that is a concern then I think I would be in favor of removing mutability entirely:

```rust
let is_container_networked = image.network().map(|network| network.starts_with("container:")).unwrap_or(false);
```

2021-12-20 11:01 UTC, jhershberg commented on src/clients/cli.rs
> +        let is_container_networked = is_container_networked;
No problem. Just fixed it. thanks!

2021-12-23 22:44 UTC, merged