Allow setting shared memory size (`shm_size`)
testcontainers/testcontainers-rs pull request #394
Opened 2022-09-09 10:32 UTC by pbillaut

2022-09-14 05:22 UTC, thomaseizinger requested changes
Thank you!

This needs to be supported in the HTTP client too before we can merge it.

2022-09-14 10:08 UTC, pbillaut commented
> Thank you!
> 
> This needs to be supported in the HTTP client too before we can merge it.

Thanks for pointing that out. Implemented the missing functionality in 681d643.

When trying to run the tests I hit #397 though, so that PR would have to be merged first.

2022-09-15 05:50 UTC, thomaseizinger approved these changes
Thank you!

Before merging please:

- Squash all commits into one
- Rebase onto master once https://github.com/testcontainers/testcontainers-rs/pull/398 is merged

bors d=pbillaut

2022-09-15 10:51 UTC, pbillaut commented
bors r+

2022-09-15 10:59 UTC, merged